services:
  db:
    image: postgres
    restart: always
    ports:
      - 5556:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: laros-watch
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
